### ISSUE TITLE
Use setuptools entry points for PyGeode plugins

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#100]
setuptools provides support for `entry_points`, which can be used for registering plugins for packages.  The idea is, each plugin registers themselves into some namespace, and then those modules are easily discovered by the main package.  This mechanism is a bit more elegant than how we do it (which is, every plugin dumps their code into pygeode/plugins/ or a special `$PYGEODEPLUGINS` directory, and PyGeode must sort it all out).  It should be possible to support both mechanisms in PyGeode, since there are no conflicts between them.

I might start a new feature branch to test this out.

**Comment by neishm** [comment]
Just committed some code which should implement this.  On the plugin side, assuming you have a module `myplugin.py`, you could have something similar to this in your `setup.py`:
```python
from setuptools import setup
setup (
        ...
        entry_points={
          'pygeode.plugins': [
            'myplugin = myplugin',
          ],
        },
)
```

Similary, if you had a custom PyGeode file format defined in `myformat.py`, the `setup.py` would look something like:
```python
from setuptools import setup
setup (
        ...
        entry_points={
          'pygeode.formats': [
            'myformat = myformat',
          ],
        },
)
```

I did some quick tests to verify that PyGeode can dynamically pick up these entries (and that the unit tests still pass).

**Comment by neishm** [comment]
I'm wondering if it might also be useful to have entry points for custom axes as well?  I've run into situations where I have my own axes, and would like PyGeode to detect and decode them from netCDF files automatically.  It would be nice if I could do something like this in my module:
from setuptools import setup
```python
from setuptools import setup
setup (
        ...
        entry_points={
          'pygeode.axis': [
            'some_nc_standard_name = mymodule.MyAxis',
          ],
        },
)
```
and then the `pygeode.formats.cfmeta` module could use this information to auto-decode axes with particular standard names.  Or, if MyAxis contains its own decoding function (if #80 is implemented). then that could be registered in the entry point.

**Comment by aph42** [comment]
Yes, this sounds like a good way to manage this once #80 is there.

**Comment by neishm** [comment]
Close this for now, since the functionality is implemented.  Fancier CF metadata hooks could be tracked within #80.

**Comment by neishm** [comment]
Just a minor typo fix for the last example (custom axes):  the plugin should register the axis as `mymodule:MyAxis` instead of `mymodule.MyAxis`, e.g.:

```python
from setuptools import setup
setup (
        ...
        entry_points={
          'pygeode.axis': [
            'some_nc_standard_name = mymodule:MyAxis',
          ],
        },
)
```
