### ISSUE TITLE
Integration with xarray+dask

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#103]
Recently stumbled across these projects that other colleagues had starred.  The [xarray](http://xarray.pydata.org) project provides functionality for manipulating arrays with physical coordinates, and the [dask](http://dask.pydata.org) project provides numerical operations on large (out-of-memory) arrays, using delayed computations.  These projects (which integrate together) overlap significantly with the functionality in PyGeode.  There may also be some other functionality which we don't fully support yet, like [multidimensional coordinates](http://xarray.pydata.org/en/stable/data-structures.html#coordinates) (see PyGeode #37).

It could be useful to have some kind of bridge between us and them, e.g. maybe functions:
* **to_xarray()** to convert `pygeode.Dataset` to `xarray.Dataset`, and convert `pygeode.Var` to `xarray.DataArray`
* **from_xarray()** to do the inverse operations.

I'm still getting familiar with these packages, but it looks like it would be a 1:1 mapping, and our `encode_cf` / `decode_cf` functions should take care of most of the details of the coordinates.  We may just need some kind of lightweight shim to go between our lazy array evaluation and theirs.

I'm planning on trying these packages out some more in the near future, and once I'm more familiar I may start work on this.

**Comment by aph42** [comment]
I'm not opposed to this by any means except that as a general comment it would be good to reduce the number of dependencies required as much as possible, so as long as this can be done in a way that doesn't require the presence of these modules, sounds good.

**Comment by aph42** [comment]
whoops, hit the wrong button...

**Comment by neishm** [comment]
I agree we shouldn't add any more dependencies.  Will try to do it in such a way that the imports will only be attempted if those functions are specifically called.

**Comment by neishm** [comment]
Also, I just noticed they have plotting as well:
http://xarray.pydata.org/en/stable/plotting.html

**Comment by neishm** [comment]
Have an initial version of the functions implemented, which should do a 1:1 mapping between `pygeode.Dataset` and `xarray.Dataset`.

### Examples

#### Converting our tutorial dataset to xarray
```
>>> from pygeode.tutorial import t2
>>> from pygeode.external import to_xarray
>>> print to_xarray(t2)
<xarray.Dataset>
Dimensions:      (lat: 31, lon: 60, pres: 20, time: 3650)
Coordinates:
  * lon          (lon) float64 0.0 6.0 12.0 18.0 24.0 30.0 36.0 42.0 48.0 ...
  * time         (time) datetime64[ns] 2011-01-01 2011-01-02 2011-01-03 ...
  * lat          (lat) float64 -90.0 -84.0 -78.0 -72.0 -66.0 -60.0 -54.0 ...
  * pres         (pres) float64 1e+03 950.0 900.0 850.0 800.0 750.0 700.0 ...
Data variables:
    Temp         (time, pres, lat, lon) float64 ...
    lat_weights  (lat) float64 ...
    U            (time, pres, lat, lon) float64 ...
Attributes:
    history:      Synthetic Temperature and Wind data generated by pygeode
    Conventions:  CF-1.0
```

#### Converting an xarray tutorial dataset to pygeode
```
>>> import xarray
>>> from pygeode.external import from_xarray
>>> data = xarray.tutorial.load_dataset('air_temperature')
>>> print from_xarray(data)
/home/mike/devel/pygeode-git/myenv/local/lib/python2.7/site-packages/xarray/conventions.py:1299: SerializationWarning: saving variable air with floating point data as an integer dtype without any _FillValue to use for NaNs
  for k, v in iteritems(variables))
<Dataset>:
Vars:
  air (time,lat,lon)  (2920,25,53)
Axes:
  time <StandardTime>:  Jan 1, 2013 00:00:00 to Dec 31, 2014 18:00:00 (2920 values)
  lat <Lat>      :  75 N to 15 N (25 values)
  lon <Lon>      :  200 E to 330 E (53 values)
Global Attributes:
  {'platform': 'Model', 'title': '4x daily NMC reanalysis (1948)', 'references':
  'http://www.esrl.noaa.gov/psd/data/gridded/data.ncep.reanalysis.html',
  'description': 'Data is from NMC initialized reanalysis\n(4x/day).  These are
  the 0.9950 sigma level values.', 'Conventions': 'COARDS'}
```
