### ISSUE TITLE
Unable to select data along an axis with underscores in the name

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#104]
Came across this weird error while trying to use the latest release (1.1.0), although it seems to be a problem in the master branch as well.

If an axis name contains underscores, then (at least in some cases) an error is thrown when trying to select data along that axis using keyword arguments.

The error I'm getting is something along the lines of:
```
  File "/some/long/path/to/pygeode/var.py", line 315, in __call__
    assert len(newargs) == 0 or ignore_mismatch, "Unmatched slices remain: %s" % str(newargs)
AssertionError: Unmatched slices remain: {'height_wrt_ground': 0.0}
```

This is after doing something like the following in my Python script:
```python
return var(height_wrt_ground=0.0)
```
On the following Var object:
```
var: <Var 'CO2'>:
  Shape:  (time,height_wrt_ground,lat,lon)  (2920,1,200,401)
  Axes:
    time <StandardTime>:  Jan 1, 2010 03:00:00 to Jan 1, 2011 00:00:00 (2920 values)
    height_wrt_ground <Height_wrt_Ground>:  1.5 
    lat <Lat>      :  90 S to 90 N (200 values)
    lon <Lon>      :  0 E to 0 E (401 values)
  Attributes:
    {'_FillValue': 1e+30, 'nbits': 32, 'ig3': 1, 'ig2': 85819, 'ig1': 95037,
    'nomvar': 'CO2', 'ig4': 0, 'typvar': 'P', 'datyp': 5, 'etiket': 'ETIKET',
    'units': 'ug(C) kg(dry_air)-1', 'grtyp': 'Z', 'specie': 'CO2'}
  Type:  Replace_axes (dtype="float64")
```

**Comment by jws52** [comment]
I've seen the same in an older version of v1.1.0. 

Perhaps the problem is confusion when identifying of the possible prefixes i_, l_, n_, m_ ?

I say this because my workaround has been to call the index along axis rather than a value. i.e.
```python
return var(height_wrt_ground=0.0)
```
would return an error but
```python
return var(i_height_wrt_ground=0)
```
would work for me.

(by the way, my first post on GitHub and using Markdown so please excuse the formatting)

**Comment by aph42** [comment]
Jake is right - this is a collision with the prefix system - (e.g. m_lat etc.). I've run in to it once or twice as well. One approach would be to change the logic if the prefix system to see if the string as it stands matches any existing axis name before decomposing the keyword argument.

**Comment by neishm** [comment]
Thanks for the tips.  Followed Peter's suggestion of checking for an axis match, seems to fix the problem.
