### ISSUE TITLE
scalar variables

### ISSUE THREAD

**Issue by aph42** [pygeode/pygeode#108]
While it is possible to create variables with no axes, there seem to be a variety of things that don't work with them. For instance,

    v = pyg.Var((), name = 'scalar', values = 10.)
    print v[()]

works, but a subsequent

    pyg.save('test.nc', v)

does not. It fails because the save routine tries to subdivide the data into chunks and the looping logic. 
There are also related problems with reading scalar variables from NetCDF files.

The issues that I have found are in `View.loop_mem()` and `View.loop_contiguous()`, specifically with what happens when they try to call `pygeode.tools.product` with an empty list of positional arguments.

I have a tentative fix for this that makes the above work (I believe) and passes the tests; for instance, the end of `loop_contiguous()` can simply be changed to 

    if len(outslices) == 0: # Handle scalar variables
      yield (), [], []
    else: 
      for outsl, insl in zip(product(*outslices), product(*inslices)):
        start = [sl.start if isinstance(sl,slice) else sl for sl in insl] 
        count = [sl.stop - sl.start if isinstance(sl,slice) else 1 for sl in insl]
        yield outsl, start, count

with a similar change for `loop_mem()`. I wanted to raise this first before committing the changes in case there are any obvious (or other) issues.

**Comment by neishm** [comment]
Thanks for catching this!  I'm surprised we've gone this long without triggering the bug.

Looking (way back) at the old SVN repository, it looks like we were originally using **itertools.product** back in 2009.  However, some of our servers were still stuck on Python 2.5, and I think things broke when I tried to use PyGeode on those machines (itertools.product was introduced in Python 2.6).  So, I created a substitute method in tools.product and switched to that in early 2010.

I just tested switching the import lines back to itertools, and the pyg.save call is working for me.  So an alternate solution could be to remove pygeode.tools.product entirely and go back to the original version.

**Comment by aph42** [comment]
That also seems to be working for reading scalar variables for NetCDF files, and is much cleaner than my suggestion.  If we're not worried about support for python 2.5 anymore (seems reasonable?) i say we go with that.

**Comment by neishm** [comment]
Sounds good to me.

**Comment by aph42** [comment]
Resolved with 4e22b4ea0fcc47730904acba49e0c390f979a696
