### ISSUE TITLE
MIgrate from Basemap to Cartopy

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#119]
Since Basemap will no longer be maintained beyond 2020, we should have a plan for migrating to Cartopy or another mapping package before then.  Considering how deeply Basemap is embedded in the plotting routines, this would probably not be feasible until a version 2.0 release where we're free to break compatibility.

https://matplotlib.org/basemap/users/intro.html#cartopy-new-management-and-eol-announcement

**Comment by admg26** [comment]
I know a bit about cartopy. Are there any other mapping packages that look like they might be viable candidates?

**Comment by neishm** [comment]
Not that I've heard of.  Cartopy is the only one I've come across so far.

**Comment by aph42** [comment]
I've also had some experience now with Cartopy. There are some annoying issues with it that I've run into, but there's also a lot of really nice aspects of it. It is frustrating that it is incompatible with Basemap (at least when I try to get a conda set up with both they conflict). However I do think that's the way to go.

I also don't think it will be a huge amount of work, the integration isn't so deep. We'll need to write a set of wrapper classes as we did for basemap then write a few routines to integrate these wrappers with the pygeode native plotting routines. Given the incompatibility with Basemap and the full switch over that will be required, I do agree that 2.0 is the time to do it.

**Comment by aph42** [comment]
I've been dabbling in this a bit recently and have gotten far enough to push a new branch ('cartopy') with some ideas. At least on my laptop, the following:

    import pygeode as pyg
    from pygeode.tutorial import t1
    pyg.showvar(t1.Temp)

produces a reasonable looking default. I'm hoping to post some examples/ideas for how to customize the map in the near future. I haven not played around much with different projections, or with quivers or barbs or streamplots...

**Comment by neishm** [comment]
Looks good so far!  I like how it can still fall back to Basemap when Cartopy isn't installed.

**Comment by aph42** [comment]
I'm going to close this since the cartopy implementation seems to be working reasonably well.
