### ISSUE TITLE
Cannot switch off showvar's colorbar as intended

### ISSUE THREAD

**Issue by jws52** [pygeode/pygeode#120]
I think related to issue #94. The following happens in a build for python2 and another for python3. 

The docstring for pyg.showvar suggests that the colorbar can be switched off by setting to False in the input args:
```
A dictionary ``colorbar`` can be provided to pass arguments through. Setting ``colorbar`` to ``False`` suppresses the colorbar.
```
However, it raises an error:
``` python
import pygeode as pyg
from pygeode.tutorial import t1
ax1 = pyg.showvar(t1.Temp,colorbar=False)
```
leads to the following exception:
``` python
/pygeode/pygeode/plot/cnt_helpers.pyc in clfdict(cdelt, min, mid, nf, nl, ndiv, nozero, style, clr, **kwargs)
    314   kwcb = kwargs.pop('colorbar', {})
    315   cb = dict(ticks = tks)
--> 316   cb.update(kwcb)
    317
    318   if not clr:

TypeError: 'bool' object is not iterable
```
Because colorbar is usually a dict, it gets confused if it's a boolean instead. Perhaps I have missed something and I shouldn't be passing it in this way, in which case the showvar docstring could be clearer.

Perhaps the easiest change is to put the boolean in the usual colorbar dict at the earliest opportunity and change the test `if cbar and cf is not None:` to `if cbar['show_colorbar_boolean'] and cf is not None:`

**Comment by aph42** [comment]
Fixed by the pull request.
