### ISSUE TITLE
Behaviour of pyg.CalendarTime.formatvalue()

### ISSUE THREAD

**Issue by admg26** [pygeode/pygeode#126]
I am wondering if I should expect the following to work:

`pyg.ModelTime365.formatvalue(453, '$d $m $y')`

It doesn't at the moment and I can see why but the problem I am trying to solve is as follows:
I have some model data that I am reading in and need to make a `TAxis` for. This axis starts on some model day say day 453.  I would like to use`pyg.ModelTime365.formatvalue(10, '$d $m $y')` to generate a start of the year that I can feed into `startdate` when creating my TAxis.

**Comment by aph42** [comment]
I'm not quite sure I've understood what you're trying to do, but am I right in that you're trying to work out what the calendar day for a time index 453 would be?

Maybe you can use the `modeltime365n` or `modeltime365range` helper functions?

For instance, if you know that the time index is relative to a fixed date, say '1 Jan 2010' or something, you can generate a reference time axis as follows:

`ax = pyg.modeltime365n('1 Jan 2010', 1)`

then `ax.formatvalue(453, '$d $b $Y'))` will return '30 Mar 2001', for instance.

But if you know the calendar date for time index 0, you can also use the constructor directly:

`pyg.ModelTime365(values = read_in_vals, units = 'days', startdate = dict(year=2010, month=1, day=1))`

**Comment by admg26** [comment]
That is exactly what I needed. Thanks!
