### ISSUE TITLE
Method to check consistency of dataset from multifile.open_multi

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#48]
Original [issue 48](https://code.google.com/p/pygeode/issues/detail?id=48) created by aph42 on 2013-11-06T15:34:04.000Z:

For speed reasons, multifile.open_multi() does not actually check the contents of all the files to confirm that the mapping from filename to timestamp is correct - in particular if a few files get corrupted during a transfer, there can be holes in this mapping and it can be tricky to find them.

As it stands, if data is requested from any such missing files, an exception is thrown.

This could be made friendlier by returning NaNs in these missing files, but it would be good to have a multifile.check_dataset() routine that explicitly locates any such missing files (or missing timesteps in the files that do exist) and reports them. This could be called once for the dataset as a check, then upon further uses of the dataset it would not need to be called.

The information of interest would be the missing timesteps - this may come from missing files (and if the filenames can be inferred that'd be cool, but not necessary), or missing timesteps in files; it would be good to distinguish these two cases.

**Comment by aph42** [comment]
This has been very useful to me and I'd like to see it exposed in the main namespace (possibly under the dataset module?). 

One issue is that it is *very* slow. I'm not sure why, but if there are ways to speed it up they would be worth it for me. 

This also may be a useful place to address some of the stuff brought up in #27 if we can look for places in the data where files are missing (perhaps by providing a date range), or where there are NaNs or missing values.

**Comment by neishm** [comment]
There are two possible reasons for the slowness that I can think of:
  1.  It scans through one variable at a time, which means if there are 30 variables in a file it has to re-scan the entire file set 30 times, from start to end.  For a large number of files, this would defeat any caching that the OS could do for us.
  2.  It only reads one timestep at a time, even if there's a month (or years) worth of data in a single file.

Both of these issues could be addressed if we change the utility to work at the file level, instead of the dataset level.  I.e.,:
  1. Take a list of filenames, and a format/opener as input
  2. Loop over each file
    * Try opening the file, and read the data, one var at a time.
    * On failure, print the filename, the variable and the type of problem (can't open file, can't read variable, NaNs in variable, etc.).

If this sounds like a good idea, I could make the changes once I have some time.

**Comment by neishm** [comment]
I have a new version of this method in a [check_dataset](/pygeode/pygeode/tree/check_dataset) branch, implemented as `pygeode.formats.multifile.check_multi`.  E.g., pass the same arguments you would normally pass to `open_multi`, and it will check if everything is consistent.  This version loops over each file in the outer loop (instead of each variable), so it _should_ be faster than the old version.

It seems to work, but probably needs more testing.  Unfortunately, I don't have any corrupted files to test with at the moment.

**Comment by admg26** [comment]
Cool. Would this be able to locate which date is missing from a dataset?
e.g. When I read in a large collection of files and I have one day missing
from a missing file.

On 15 April 2016 at 22:42, neishm <notifications@github.com> wrote:

> I have a new version of this method in a check_dataset
> <http:///pygeode/pygeode/tree/check_dataset> branch, implemented as
> pygeode.formats.multifile.check_multi. E.g., pass the same arguments you
> would normally pass to open_multi, and it will check if everything is
> consistent. This version loops over each file in the outer loop (instead of
> each variable), so it *should* be faster than the old version.
>
> It seems to work, but probably needs more testing. Unfortunately, I don't
> have any corrupted files to test with at the moment.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pygeode/pygeode/issues/48#issuecomment-210658461>
>



-- 
Alison Ming

**Comment by neishm** [comment]
Just pushed some updates which should do that.  It won't tell you the exact name of the missing file (since there's no mapping from dates back to filenames), but it will tell you the name of the known file right _before_ the gap occurs.

**Comment by admg26** [comment]
That is very helpful. Thank you!

**Comment by neishm** [comment]
If this new method works, I'm planning on removing the old `check_dataset.py`.  The way it's designed, it's very limited in the types of errors it can catch.  It's also limited in the details of the error report (e.g. it doesn't know anything about the source files).
