### ISSUE TITLE
formats.netcdf missing some netcdf data types

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#54]
Original [issue 54](https://code.google.com/p/pygeode/issues/detail?id=54) created by neishm on 2014-01-10T15:40:22.000Z:

Just tried opening one of the netCDF files provided by ObsPack (http://www.esrl.noaa.gov/gmd/ccgg/obspack/), but I get the following exception (in v0.7.2):

  File &quot;&lt;string&gt;&quot;, line 1, in &lt;module&gt;
  File &quot;/usr/lib/pymodules/python2.7/pygeode/formats/netcdf.py&quot;, line 411, in open
    dataset.atts = get_attributes (fileid, -1)
  File &quot;/usr/lib/pymodules/python2.7/pygeode/formats/netcdf.py&quot;, line 72, in get_attributes
    valnp = empty([size.value], numpy_type[vtype.value])
KeyError: 10

We don't have data type 10 (signed 8-byte integer) handled in our module.  In fact, we only have the first 6 data types out of 12.  The full list of data types (as of netcdf 4.1.1) is:
# define NC_NAT          0       /\* NAT = 'Not A Type' (c.f. NaN) */
# define NC_BYTE         1       /\* signed 1 byte integer */
# define NC_CHAR         2       /\* ISO/ASCII character */
# define NC_SHORT        3       /\* signed 2 byte integer */
# define NC_INT          4       /\* signed 4 byte integer */
# define NC_LONG         NC_INT  /\* deprecated, but required for backward compatibility. */
# define NC_FLOAT        5       /\* single precision floating point number */
# define NC_DOUBLE       6       /\* double precision floating point number */
# define NC_UBYTE        7       /\* unsigned 1 byte int */
# define NC_USHORT       8       /\* unsigned 2-byte int */
# define NC_UINT         9       /\* unsigned 4-byte int */
# define NC_INT64        10      /\* signed 8-byte int */
# define NC_UINT64       11      /\* unsigned 8-byte int */
# define NC_STRING       12      /\* string */

It should be straight-forward enough to add in types 7..11 in our module (just extend a few lookup tables).  Type 12 will be more tricky, since it allows for strings of arbitrary length.  For full compatibility with netCDF, though, they should all be handled.

**Comment by aph42** [comment]
I came across this issue recently (there was a type 12 variable in a netcdf file) - it wasn't important and I could work around it but what is required to add type 12?

**Comment by neishm** [comment]
That's a good question.  To start with, having a test file with type 12 data would help :) (I haven't come across one yet).  Next, we'd have to find some way of encoding a numpy array such that each element is a self-contained string of variable length.  I know there's dtypes like '|S12' e.g. for *fixed* length strings of length 12.  We may have to fall back to a generic 'object' dtype to store arbitrary strings.  
Re-encoding to netcdf would require us to first check for Vars with generic 'object' dtype, then check all the objects for 'str' type, then encode them as an array of char* pointers in C, then call the appropriate netcdf write routine.

I haven't personally encountered this type yet, so I hadn't considered it a priority for release-1.1.

**Comment by aph42** [comment]
Ok, given that 7-11 are handled now and 12 is rarely seen in the wild i've downgraded this to low priority; I'll see if I can get my hands on a file with such a variable to test things out, but my inclination is to find a way to fail gracefully if such a variable is found, rather than putting the effort into handling it. This may already be the case but I seem to recall that the file couldn't be used even for other variables. If I can find such a file I'll take a look.

**Comment by neishm** [comment]
Ok. If you find such a file, and it doesn't fail gracefully, I'll try patching it up (print a warning message, and skip the variable?)

**Comment by neishm** [comment]
With the implementation of #101, I don't think this is a priority anymore.  It would be easier to switch to the `formats.netcdf4` module for these data types, instead of trying to re-implement the functionality in this module.
