### ISSUE TITLE
Pygeode configuration file

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#62]
Original [issue 62](https://code.google.com/p/pygeode/issues/detail?id=62) created by aph42 on 2014-09-04T17:38:04.000Z:

There are a handful of parameters that I'd like to be able to set globally without having to change the source files, and quite a few details in the axes descriptions and plotting packages that would be good to have some way of customizing. 

We've discussed having configuration files before; I was looking at the built in ConfigParser module (https://docs.python.org/2/library/configparser.html#module-ConfigParser) which looks like it would make implementing this pretty easy. The format would be basically a bunch of categorized name value pairs, I've attached a sample file with a few thoughts. 

One question is defining a set of directories to look for config files; the behaviour here

https://docs.python.org/2/library/configparser.html#ConfigParser.RawConfigParser.read

makes this quite convenient - my thought was the current directory followed by the user's home directory, followed by a default in the library path. These could be read in **init** and exposed as a ConfigParser object (or possibly as a dictionary?) in the pygeode namespace (say pyg.rc), which would then be accessed by any bits of the code needing the value of those parameters, and could thus be modified on the fly (ish). 

I'm happy to implement this if that sounds good.

**Update:**
List of things to control with the configuration file (edit this list as you think of new things):
- [x] Memory limits (array size, swap size)
- [ ] Plot formatting
- [ ] Name-mangling of single-variable operations

**Comment by aph42** [comment]
I'd like to see much more use of the configuration file in 1.1. Still not 100% sure on the general use of it (as per discussion above) but regardless, I agree with having it in 1.1. Mostly in terms of having control over formatting issues.

**Comment by neishm** [comment]
One other thing that would be useful for me would be to control whether variables get renamed after a single-variable operation.  For example, doing a derivative of variable "xyz" gives a new variable named "d(xyz)", and doing a monthly mean of variable "abc" gives a new variable named "abc_monthlymean".  In my current diagnostics, I'm having to force the name back to the original at the end of each operation.

I was going to propose adding an extra argument to each of these methods, to tell them not to clobber the name.  However, controlling this centrally from a configuration file would be more elegant.

**Comment by neishm** [comment]
Let try something out...

Things to control with the configuration file:
- [x] Memory limits (array size, swap size)
- [ ] Plot formatting
- [ ] Name-mangling of single-variable operations

**Comment by neishm** [comment]
I added a "task list" in the first comment of this issue, to keep track of what behaviour we plan to control from the configuration file (and also indicate the progress of these features).  I thought I'd try it out after seeing it mentioned on the [markdown page](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown).

**Comment by aph42** [comment]
I agree (months later) that having an option for what to do with the variable names might be useful.

**Comment by aph42** [comment]
I've also added a new topic branch called axis_rc in which axes objects read some of their basic configuration details from the configuration file. There are still some things that would be nice to have configurable along these lines (such as the ticking rules for automatic formatting of time axes, also possibly colourmap defaults) which are a bit less trivial. I wanted to put this in a branch before merging it in since versions of this have already triggered a couple of subtle errors in my code. I'm also a bit worried about performance when creating large numbers of variable objects for a big dataset; haven't done any profiling of that.

Finally I'd also love to get the cf stuff refactored to use this better as well.

**Comment by neishm** [comment]
Thanks for taking the initiative on this!  I think it's coming along nice.  Just one suggestion.

I noticed that `_readaxisconfig` is called during `__init__` time, which means it's done over and over again when a new axis is created of that type.  This could lead to a small performance hit.

I was going to recommend calling this method directly in the class definition, but then it's impossible to get a reference to the class (since it's not technically defined yet).

What could work, is if there was a decorator to modify the class, e.g. something like
```python
def autoconfig (cls):
  # put body of _readaxisconfig here, treating 'cls' as 'ax'
  # (don't need a particular instance object)
  # ...
  return cls  # Return the class after the properties are updated
```
and then for each class, prepend the decorator:
```python
@autoconfig
class Lat(YAxis):
  # ...
```
Note that each axis subclass would need this decorator at the beginning of the class definition, in order for it to use the config file.  I think it's possible to further automate things with metaclasses so we don't need a decorator or anything, but that would be extreme overkill.  Besides, having the decorator at the beginning makes the extra class modifications more discoverable (in my opinion, anyway).  It also gives some control over whether to use a config file for an axis type, by including/omitting the decorator (i.e. quick-and-dirty custom classes can omit the decorator and skip the config file entirely).

**Comment by neishm** [comment]
I recently came across a nice little module called [appdirs](/ActiveState/appdirs) which encapsulates the logic for finding system-wide and per-user config files, for any OS.  One drawback, though, is it doesn't give the exact same directories we're assuming (it's giving me `~/.config/pygeode/` for the per-user config directory, and `/etc/xdg/xdg-ubuntu/pygeode/` for the system-wide config directory on Ubuntu).  However, it's going to give the "standard" locations recommended by the OS, so it might be worth switching to this module?  It's a single Python module, which the author says can be easily embedded in other packages.

**Comment by neishm** [comment]
Merged in whatever was started in the `axis_rc` branch, so at least some of the configuration file feature will be available in release 1.1.
Re-targeting release 1.2 for any missing pieces.

**Comment by neishm** [comment]
Are there any updates for this feature that would be useful for a version 1.4?

**Comment by aph42** [comment]
At the moment there are various plotting details that can be configured, but the variable renaming policy is not implemented, nor is the cf refactoring. I don't want to tackle the latter, but the former should be easy enough. I haven't looked further into appdirs - would it require a new dependency?

**Comment by neishm** [comment]
Looks like appdirs would become another dependency if we choose to use it, but it's on PyPI so we'd just need to add it to the list of dependencies in setup.py.

**Comment by aph42** [comment]
The topic of variable renaming conventions came up again in a recent conversation with @admg26; we felt the right way to move forward ultimately is would be to keep the renaming to a minimum, but to add more detail in the attributes of the variable to keep a better log of what operations had been carried out (like how nco works). 

Both the cf metadata refactoring and the renaming seem like a bigger projects that probably deserve their own issue/feature suggestion, so I'm going to close this for now.
