### ISSUE TITLE
Ability to edit Datasets in-place

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#63]
Original [issue 63](https://code.google.com/p/pygeode/issues/detail?id=63) created by neishm on 2014-09-15T16:29:10.000Z:

There have been a couple of instances recently where I wanted to do a quick fix on an existing Dataset object, such as scaling / offsetting some of the variables inside.  

I've had to resort some roundabout method, like
1) Convert the Dataset to a list.
2) Find the variable(s) I'm interested in, and modify them in the list.
3) Collect the list of variables back into a new Dataset.

It's workable, but not very elegant.  It would be nice to be able to modify the variables of the dataset in-place, like:

mydata.P0 *= 100  # Convert from hPa to Pa

or

mydata['P0'] *= 100

It should be easy enough to add this functionality with an appropriate __setattr__() and __setitem__() method in Dataset.  However, there may be some unexpected behaviour to deal with, like what happens if the new variable has slightly different axes (with the same names)?  We would have to take care not to stomp on the existing axes in the Dataset.  Also, we'd have to check that the new variable's name is the same as the specified key / attribute name, otherwise we'd need to rename the variable.

I can take a crack at implementing this, if it seems like something worthwhile.

**Comment by aph42** [comment]
What about using map? I've been finding this super useful recently; so something like

def rescale(v):
   if [v in set of vars to fix]: return (v*100).rename('v')
   else: return v

then a simple ds1 = ds.map(rescale) does the trick.

I'm not opposed to making datasets editable in place but given that everything else is immutable I'm inclined to leave it that way unless you think this is still too awkward. That being said as I am getting more into using datasets for active processing I'm very much open to new useability features.

**Comment by neishm** [comment]
I've used `map` as well when I need to quickly change everything in a dataset.  However, for my particular case I just have a single variable I need to scale at a time, and I don't want to touch the other ones.  You're right that it would break immutability, though.  Maybe a compromise would be having an easy way to convert back and forth between a Dataset and some mutable structure (like a dict?).  E.g., if I could do
```python
mydata = dict(mydata)
mydata['P0'] *= 100
...
mydata = Dataset(mydata)
```
then I think that would be good enough for me...

**Comment by aph42** [comment]
I'm certainly happy with the suggestion to go back and forth; the behaviour below could be done at present by

```python
mydict = mydata.vardict.copy()
mydict['P0'] *= 100
mydata2 = Dataset(mydict.values())
```

Adding an option to the constructor to take a dictionary as an argument would be easy and worthwhile. Is it easy to implement the kind of automatic casting to a dictionary you've suggested? There is a bit of ambiguity in that one might in principle be interested in the axes dictionary, though that could always be accessed as above.

Just to point this out one can still use map to work on small numbers of variables; for instance

```python
def mod(v):
    if v.name == 'P0': return v*100
    else return v
```
would get you there.

**Comment by neishm** [comment]
Your first example is pretty much what I wanted to do anyway, without having to add any new code to Dataset. I'm removing this from the release milestone, but I'm leaving it open for the time being. My short-term memory is terrible, and I don't want to lose this useful information :P
