### ISSUE TITLE
Allow Var objects for auxarrays

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#65]
Original [issue 65](https://code.google.com/p/pygeode/issues/detail?id=65) created by neishm on 2014-12-03T15:56:16.000Z:

When creating a new axis, if you try to pass in Var objects as auxarray arguments (e.g. for A and B arrays of Hybrid axes), they get stored as auxatts instead.  Would be be nice if `Axis.__init__` detected Var objects, and extracted the numpy arrays from them automatically and put them in the auxarrays, or at least complain about getting a Var object.  Right now, it silently takes the arguments, puts them in the wrong container (auxatts), and the axis doesn't behave properly.

**Comment by aph42** [comment]
This hasn't come up for me but it sounds like sensible behaviour so I'm happy with this change. 1.1?
