### ISSUE TITLE
Gracefully handle missing GSL library

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#75]
Right now, PyGeode will crash with an ImportError if the GSL library is not found.  It would be nice if to have a try/except block to catch any problems, print a warning message, and disable interpolation if necessary.  We already do something similar with the netcdf library.

**Comment by aph42** [comment]
I'd like this in 1.1. Despite being the one who suggested using an external library for interpolation it is annoying to have GSL in the stack for one task only. It'd be nice to move away from gsl but it would mean implementing all the different interpolations ourselves which is not something I want to deal with. Having at least linear interpolation in the absence of GSL would be good though, and probably not too onerous a task.

**Comment by neishm** [comment]
Other annoying things with GSL:
* Doesn't work efficiently on multi-dimensional arrays.  We have to do the looping over the other non-interpolated axes ourselves, which involves fun stuff like pointer manipulation.  Also involves an initialization call to GSL for every iteration of the loop, which probably adds more overhead.
* Coordinate must be increasing, which means we have to reverse the order ourselves when we have a decreasing coordinate.
* Doesn't handle missing values - we* have to manually loop though the data and filter these out before we can start interpolating.
* Doesn't extrapolate - we* had to implement our own extrapolation step after the interpolation part.

\*by *we*, I mean you did the actual work :P

Looking forward to the day we can replace GSL, but gracefully disabling interpolation should be a short-term fix for now...

**Comment by aph42** [comment]
Agreed on all of the above :) For 1.1 lets stick with the short term fix, but it's good to have this documented.

**Comment by neishm** [comment]
Just pushed a fix for this issue.  Note that this only fixes a missing GSL library at runtime; you still need the GSL header files to compile the extension module in the first place.

Would it also make sense to allow for a missing GSL library at compile time?  That would require a bit more work, to figure out how to conditionally compile the extension module...

**Comment by neishm** [comment]
Added some compile-time control with commit e15c63fe9a53ae67d175d59ca770ac9bd30180e1.  Closing this issue.

**Comment by boardgamedev** [comment]
On Windows, the missing GSL library causes the install to throw an error and fail. I will email you a stack trace.

**Comment by admg26** [comment]
On Windows, the missing GSL library causes the install to throw an error and fail. I will email you a stack trace.

**Comment by neishm** [comment]
Could you try installing the gsl package from conda?
```
conda install -c conda-forge gsl
```
That should give you the necessary header files.

**Comment by admg26** [comment]
We tried that and it didn't work for either the MacOS or the windows people. @aph42 is going to try debugging this on his Windows partition.

**Comment by neishm** [comment]
Ok.  Unfortunately I don't have a viable Windows machine here, so can't be of much help.  If I download the conda GSL package and manually extract the files, I do see `gsl/gsl_interp.h`, so the headers should get installed *somewhere*.  Maybe the `pip install` command doesn't see the include paths from the anaconda environment?

**Comment by admg26** [comment]
I am not sure because I did the same set up as everyone else and it worked for me. This happens for some people too under linux and I am going to dig into that.

**Comment by aph42** [comment]
I had a go at this on my Windows partition last night and ran into an error saying I needed to install Microsoft Visual Studio build tools. I did that and that didn't fix the issue, so I'm still at a loss. I did come across some threads suggesting that i should upgrade pip, so I might try that next.
