### ISSUE TITLE
Segmentation fault when constructing time axis with big month value

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#76]
One-liner to trigger:
```python
time = pyg.StandardTime(month=[1600])
```
1600 was around the minimum value I needed to trigger the seg fault (using 1500 didn't crash).  This value may be OS and machine-dependent.

**Comment by aph42** [comment]
Can confirm. Takes a long time to do so, too; 1500 was find, 1580 crashed.

**Comment by neishm** [comment]
The root cause was the `month2doy` array in the C code, used to calculate the day of year.  There was no sanity check on the month provided, so anything > 12 was actually accessing some arbitrary area of memory.

I pushed a fix to check the month value and raise an `IndexError` when it's out of bounds.  I'm not sure what I was originally thinking when I ran this code.  Maybe I was hoping it would auto-wrap the dates so year 0 month 13 would become year 1 month 1?  Anyway, that should go in a separate feature request if it's ever needed.
