### ISSUE TITLE
Interpolate transposes axes

### ISSUE THREAD

**Issue by aph42** [pygeode/pygeode#77]
One minor irritation I have with the interpolation stuff in pygeode is that it transposes axes on you at the same time. I know this is done for memory reasons under the hood but I'd prefer to re-transpose stuff back to the original order after the interpolation has been performed (which is straightforward enough).

Would there be an issue with changing this behaviour?

**Comment by neishm** [comment]
Yes, I'm finding this behaviour annoying myself.  I have to remember to un-transpose the axes after every interpolation.

Having said that, we have to be careful about breaking backwards compatibility with v1.1.  It's possible someone's scripts are built around the current behaviour (e.g., they interpolate, then assume the last axis is the interpolation axis when they manipulate the field later on).  These hypothetical users (if they exist) shouldn't expect things to break with a minor version increment.

http://semver.org/

What about adding a keyword parameter like "transpose_axes", and set the default to True for now?  That way, current scripts will behave the same, but we at least have the ability to override the behaviour as needed.  Near the end of the release-1.x lifetime, we can print a warning when the user doesn't specify this parameter, and tell them they should explicitly set transpose_axes=True if they want their scripts to work in the future.

A separate issue could be filed for a future release-2.0 milestone, where we can collect all the annoying things that we want to change all at once (and give no guarantee that existing user scripts will continue to work without modification).  At that release, we can change these defaults around to suit our own preferences...

**Comment by aph42** [comment]
Fair enough - it feels a bit like we're being overly conservative given that I don't think there's a huge user base :). 

Nonetheless I'm happy with this suggestion but would like the keyword to be as short as we can make it (and still clear) given that I'll be getting into the habit of using it all the time. 'transpose' I think has the same information content as 'transpose_axes' and shares the name with the command you'd use to do the same thing so it's probably better to stick with that rather than going to something like 'fix_axes' or 'reorder' or 'order' or something.

I'll add this to 1.1 unless there are objections.

**Comment by neishm** [comment]
Okay, 'transpose' sounds good to me.
