### ISSUE TITLE
Installation and libary problems on Macs

### ISSUE THREAD

**Issue by aph42** [pygeode/pygeode#78]
I've had a few people want to install pygeode on a mac recently and have cooked up an anaconda recipe/package for it. At least within the anaconda context, there has been problems with both the setup.py installation not finding necessary include files, and with pygeode itself not finding runtime libraries. Both of these are down to path issues and I think I have fixes for them (in setup.py and libhelper.py; the latter I've rather generalized. )

I'd like to update the 1.0 release branch with these (and will bring them into the main branch as well for 1.1, but I'm actually not 100% sure how to test them. I can do so at least on my laptop and on my dad's macbook but I'm worried about fresh installations and other os' etc. and have no idea how to test them beyond pushing the changes and hoping for the best. If there isn't a big objection I'll do that (since I don't think 100s of people are going to be affected if things break a bit along the way :). 

This is much about documenting this as anything else, but Mike, if you could confirm this that'd be good.

**Comment by neishm** [comment]
Could you start a new topic branch (either off of master, or release-1.0), and commit your changes there?  I'm curious to look at the changes, and some info on the problems you've encountered along the way.  I'd also like to run some tests to make sure things still compile/install properly on my end.

**Comment by neishm** [comment]
Hi Peter,

I'm having a look the changes now (3514d71be041db9195ff8aca6d3bd26ff652e7a1).  I don't see any major issues it.  Normally, I'd be concerned about doing code re-factoring in a bug fix (e.g. the new `get_library_paths` method).  But it seems minor enough that it *probably* won't break anything.

Which libraries was it having difficulty finding?  As far as I know, the `find_library` method is only used by the `load_lib` method, which in turn is only invoked for the netcdf and hdf4 interfaces.  We used to need this interface for all our compiled code (interpolation, time axis manipulation, etc.).   Now that we use extension modules, I thought at least 75% of these search paths were obsolete?

**Comment by neishm** [comment]
Anyway, if these changes are sufficient for your mac and anaconda releases, we can tag a new v1.0.4 release from this.  The libhelper module for the master branch has changed since release-1.0 (I cleaned up some paths which are not needed anymore), so the changes may need to be manually recreated there...

**Comment by aph42** [comment]
Hi Mike,

The issue was with netcdf and hdf libraries - which are kind of 
important. There were two issues, one that on macs the library 
extensions seem to be .dylib sometimes instead of .so or anything, and 
the other is that anaconda puts everything under a local prefix to keep 
installations independent from the system (and each other). Having 
access to the paths was useful for debugging purposes. The changes to 
setup.py were to correct a similar issue with anaconda finding the right 
header files.

I'll merge the changes into release 1.0 branch and tag v1.0.4 (this is 
also needed for the anaconda installation to pick up on the changes). I 
can fold them into the master branch manually as well.

Peter

**Comment by aph42** [comment]
Ok - I've made the changes both to the release1.0 and master branches. There are updated conda packages for pygeode1.0.4a (linux and osx for now) at https://conda.anaconda.org/aph42.

**Comment by neishm** [comment]
Thanks, Peter.  I just pushed one extra update to release-1.0 (to update the changelog and the version number).
