### ISSUE TITLE
time axis creation helpers

### ISSUE THREAD

**Issue by aph42** [pygeode/pygeode#81]
I've added a set of helper functions to timeaxis.py (and to the main namespace) to simplify creating time axes: there are two styles for each calendar type: <type>range and <type>n. So for instance, to create a ModelTime365 axis starting from 1 Jan 2000 to 1 Jan 2001, you can write

```python
pyg.modeltime365range('1 Jan 2000', '1 Jan 2001') 
pyg.modeltime365range('1 Jan 2000', '1 Jan 2001', step=6, units='hours') 
pyg.modeltime365range('1 Jan 2000', '1 Jan 2001', From='1 Jan 1990')
```

Hopefully the above are all intuitive; the default step size is 1 (in terms of the specified unit), and the default unit is 'days'. The default startdate is the same as the start date, but it can be specified with the From keyword (the capital was necessary to avoid the keyword)

The other version is for an axis of given length:

```python
pyg.modeltime365n('1 Jan 2000', 365) 
pyg.modeltime365n('1 Jan 2000', 365, step=0.25)  
```

units and From can also be specified.

I've already implemented all of these, but I thought I'd document these to solicit comments.
so the latter would still be length 365 and would only capture a quarter of the year.

**Comment by neishm** [comment]
Thanks, Peter.  I don't usually generate time axes from scratch, but I imaging these helpers will come in handy for those situations.

What about using 'ref' or 'reference' for the start date, to avoid capitalization?

**Comment by neishm** [comment]
Closing, since this has already been implemented.
