### ISSUE TITLE
Move operations to more consistent locations in the library

### ISSUE THREAD

**Issue by aph42** [pygeode/pygeode#83]
There are a handful of 'orphaned' or otherwise less than obvious bits of functionality that seem more awkward to use (and to document) than they need to be. I'd like to suggest the following:
- add 'concatenate' to top-level namespace 
  This could be done as a synonym for concat.concat(); one issue is how to deal with the dataset version of this; I'm not sure.
- 'asdataset' to top-level namespace
  To me this seems useful enough to have in the top-level namespace
- hook 'composite', 'flatten', 'fft_smooth', and 'lag' as member functions of Var
  All but the last of these take a var as a first argument and are natural member functions. There isn't a lag helper function for the Lag class in timeutils.py, but there should be, and it would also be a natural addition.
- rename 'ensemble' module to 'ens', add 'ensemble', 'make_ensemble', to top level?
  I don't use these much to be honest, though it does seem like a potentially useful feature. However 
  right now ensemble is the name of the module so something would have to be renamed to retain access to the module.

All but the last retain backward compatibility; I'm happy to leave the latter as some kind of future change, though i think it could be cleaner than it is, so it would be good to keep this in mind.

I've added this to 1.1 as it's a 10 minute job and mostly housekeeping.

**Comment by neishm** [comment]
I'm ok with all but the last one, for the same reason you state (backward compatibility). I've created another milestone (release-2.0) which could include renaming 'ensemble' to 'ens'. It's probably nitpicking, but I'd rather save all these minor compatibility breaks for one big update in the future.

**Comment by neishm** [comment]
All updates (except the "ensemble" one) have been implemented in the master branch.

**Comment by aph42** [comment]
There is an issue with the top level concat function which has been added which is that it makes the concat module inaccessible. I happen to have a bunch of code that uses pyg.concat.concat (or variants of this) which is broken by this. The issue 69 regression test is also broken - I suggest renaming the function 'concatenate.'

**Comment by neishm** [comment]
Whoops, sorry about that.  I tested that the new top-level method worked, but didn't notice the name collision with the concat module.  'concatenate' sounds good to me.

**Comment by aph42** [comment]
Ok - I've renamed it concatenate in commit ea0b2da
