### ISSUE TITLE
Reduce subspace of iterative EOF routine

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#84]
EOF unit test is failing (at least for me).  In the end, I'm getting the message:

> ValueError: On entry to DLASCL parameter number 4 had an illegal value

and all my eigenvalues are zero.  Traced the issue to the size of the subspace used.  We solve for more eigenvalues than necessary, in the hopes that we'll be more well separated from the uncomputed eigenvalues (and thus, converge faster with the power method).  The formula used to compute the subspace is:

``` python
subspace = 2*num + 8
```

which means, even for computing a single eigenvector in the test script we need to keep track of the top 10 eigenvectors, and solve 10x10 covariance matrices.
Even worse is for the `EOF_guess` stage, where we concatenate two sets of eigenvectors together to solve for "merged" eigenvectors.  This doubles (quadruples?) the covariance to 20x20, which (for the test data) is pushing us beyond the capacity of lapack.  We're getting negative eigenvalues for some of the smaller components, which get translated to NaNs later on and ultimately screws up the entire solver.

The safest thing would be to set the subspace equal to the actual space we're interested in by default, and not pad it with extra entries that might not be numerically resolvable.  The trade-off is this could slow down convergence, though.  However, you could always pass an explicit `subspace` value directly to `EOF_iter` and speed things up when it's safe to do so.

Any thoughts on changing the default subspace?  Has this been an issue for anyone else?

**Comment by aph42** [comment]
I'm afraid I'm just now catching up to this - to be honest I haven't used these methods; I've tended to work with EOFs of spaces that could be handled directly (though I recognize that has been a matter of chance; that's not always convenient). 

At the moment the EOF unit test is segfaulting on my machine; this may be an issue with the way it's calling my lapack libraries but in trying to track it down it started to evade my tracing printf calls in mysterious ways and I have now lost steam. It doesn't seem to matter what size variable I pass, EOF_iter and EOF_guess both segfault....

Ideally it would be good to have some sense of whether the convergence succeeded or not - at that point one is left with digging into details anyways, the main concern is not realizing that the EOF guess has failed...

**Comment by neishm** [comment]
I was able to get it working if I remove the line
```python
if subspace <= 0: subspace = 2*num + 8
```
from `eof.py`, which effectively sets the subspace equal to `num` (no extra eigenvalues computed).  Mine wasn't segfaulting, though (just exiting), so it may have been a different problem?

**Comment by neishm** [comment]
Pushed the workaround in a11e7b12476d073c7ef88fa3239c00c28629cac9.  Fixes the EOF unit test for me, hopefully it will make things more stable in general.  Maybe it's possible that under some circumstances it was choosing a subspace that was larger than the space of the covariance matrix, causing some instability in the lapack routines?

**Comment by neishm** [comment]
Haven't had/heard any problems, so assuming this fix is okay.

**Comment by aph42** [comment]
This segmentation fault issue was causing me problems again - I tracked it to a name collision issue (I think) with the local function dysev() in eof.c. I've renamed that function dysev_pyg()  - it is a local wrapper for the lapack function dysev. That seems to correct the issue on my machine.

**Comment by neishm** [comment]
I don't use this function myself outside the unit tests.  Is there some kind of de-facto test data that people use for demonstrating EOFs?  It's been a while since that C code has been worked on, and I'd be curious to see how efficient it actually is...

**Comment by aph42** [comment]
I haven't either, but I've avoided it because of these intermittent segfaults and actually might more often now that it should work more reliably for me. I don't know of standard test data or of analytical results; this has gotten me down a rabbit hole looking at EOF literature in climate science and most of the reviews I've come across use well-known cases (such as monthly mean MSLP data), but not in a standardized, reproducible fashion.

**Comment by neishm** [comment]
I think I'm going to comment out all those printf statements in eof.c.  Most of the information was only useful during the development stage, not relevant to the end user.
