### ISSUE TITLE
Add getaxis, hasaxis, and whichaxis to Dataset interface

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#93]
I've run into this a couple of times, where I want to look up an axis in a `Dataset` and don't know a priori what the name is (just the class name or type).  We have this functionality in `Var` objects, so it makes sense to include it in `Dataset` objects too.

**Comment by aph42** [comment]
Sounds good, makes sense to have it.

**Comment by neishm** [comment]
Implemented `getaxis` and `hasaxis`.  Not implementing `whichaxis` because Datasets don't have an intrinsic order to the axes.
