### ISSUE TITLE
Release of v1.1.0

### ISSUE THREAD

**Issue by neishm** [pygeode/pygeode#98]
I know there's still some unfinished work that was targeted for the release-1.1 milestone.  However, considering how much time has passed since release-1.0, I was thinking maybe we should just release what we have and re-target the unfinished work for a release-1.2?

@aph42 would you have any concerns with doing that?

**Comment by neishm** [comment]
Haven't heard anything, so assuming it's okay to go ahead with a release-1.1 branch.  Will start some alpha releases for testing.

**Comment by aph42** [comment]
Apologies for the radio silence. I've merged in some 'recent' changes including a significant improvement to the error checking in the interpolation code (i.e. it doesn't segfault when confronted with non-monotonic data, instead a helpful error message is given). I think this is all a good plan. I've had a few regression tests fail on me after updating my repo though; I'm going to check on them.

**Comment by neishm** [comment]
Thanks for the updates, Peter!

**Comment by neishm** [comment]
One update I recently made was the switch from `distutils` to `setuptools` in our setup script.  This was done for a couple of reasons - to allow building "wheel" files (and maybe uploading to PyPI at some point?), and also because distutils is now deprecated.  Hopefully it doesn't break anything, but worst case we can just "git revert 8a4503ae3a1c8998a8b94b003da53e51bdeec4a7" for this release.

**Comment by neishm** [comment]
Unit tests are all passing for me now, and I don't see anything else left in the milestone.  Release time?

**Comment by neishm** [comment]
There's been no code updates since May 5, so I'm assuming things are stable now.  Released version 1.1.0.  Any further bug fixes can go into a v1.1.1 release (on the release-1.1 branch), and new features can go in the master branch.
